# roles/helm/handlers/main.yml
---
- name: Update Helm repositories
  ansible.builtin.command:
    cmd: helm repo update
    creates: /path/to/some/file/that/indicates/repo/updated
  tags:
    - helm
    - configuration
