# roles/helm/tasks/main.yml
---
- name: Check if Helm is installed
  ansible.builtin.command: helm version --short
  register: helm_check
  changed_when: false
  failed_when: helm_check.rc != 0
  ignore_errors: true
  tags:
    - helm
    - check

- name: Download Helm script
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
    dest: /tmp/get_helm.sh
    mode: "0700"
  tags:
    - helm
    - install
  when: helm_check.rc != 0

- name: Install Helm
  ansible.builtin.command: /tmp/get_helm.sh
  args:
    creates: /usr/local/bin/helm
  tags:
    - helm
    - install
  when: helm_check.rc != 0

- name: Add Helm repositories
  ansible.builtin.command: "helm repo add {{ item.name }} {{ item.url }}"
  loop:
    - { name: "stable", url: "https://charts.helm.sh/stable" }
    - { name: "bitnami", url: "https://charts.bitnami.com/bitnami" }
    - { name: "ingress-nginx", url: "https://kubernetes.github.io/ingress-nginx" }
  tags:
    - helm
    - configuration
  register: helm_repo_add
  changed_when: helm_repo_add.rc == 0 and "has been added" in helm_repo_add.stdout
  notify: Update Helm repositories

- name: Install NGINX Ingress Controller with custom ports
  ansible.builtin.command: >
    helm upgrade --install nginx-controller ingress-nginx/ingress-nginx
    --set controller.service.type=NodePort
    --set controller.service.nodePorts.http=30080
    --set controller.service.nodePorts.https=30443
    --kubeconfig /etc/rancher/k3s/k3s.yaml
  args:
    creates: /usr/local/bin/nginx-controller
  tags:
    - helm
    - nginx
