all:
  children:
    k3s_cluster:
      children:
        master:
          hosts:
            dev-master-1:
              ansible_host: 34.229.97.247 # Thay đổi IP này
              ansible_ssh_private_key_file: ../terraform/keys/dev-master-1.pem
        worker:
          hosts:
            dev-worker-1:
              ansible_host: 98.84.155.203 # Thay đổi IP này
              ansible_ssh_private_key_file: ../terraform/keys/dev-worker-1.pem
