all:
  vars:
    ansible_user: ubuntu
    bastion_host: "{{ hostvars['dev-manager-1'].ansible_host }}"
    bastion_user: ubuntu
  children:
    k3s_cluster:
      children:
        manager:
          hosts:
            dev-manager-1:
              ansible_host: "{{ instances[0].public_ips }}"
              dns_name: "{{ instances[0].dns_name }}"
              private_ip: "{{ instances[0].private_ip }}"
              ansible_ssh_private_key_file: "{{ key_path }}"
        master:
          hosts:
            dev-master-1:
              ansible_host: "{{ instances[1].private_ip }}"
              private_ip: "{{ instances[1].private_ip }}"
              ansible_ssh_private_key_file: "{{ key_path }}"
              ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ProxyCommand="ssh -W %h:%p -i {{ key_path }} -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null {{ bastion_user }}@{{ bastion_host }}"'
        worker:
          hosts:
            dev-worker-1:
              ansible_host: "{{ instances[2].private_ip }}"
              private_ip: "{{ instances[2].private_ip }}"
              ansible_ssh_private_key_file: "{{ key_path }}"
              ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ProxyCommand="ssh -W %h:%p -i {{ key_path }} -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null {{ bastion_user }}@{{ bastion_host }}"'
            dev-worker-2:
              ansible_host: "{{ instances[3].private_ip }}"
              private_ip: "{{ instances[3].private_ip }}"
              ansible_ssh_private_key_file: "{{ key_path }}"
              ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ProxyCommand="ssh -W %h:%p -i {{ key_path }} -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null {{ bastion_user }}@{{ bastion_host }}"'
            dev-worker-3:
              ansible_host: "{{ instances[4].private_ip }}"
              private_ip: "{{ instances[4].private_ip }}"
              ansible_ssh_private_key_file: "{{ key_path }}"
              ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ProxyCommand="ssh -W %h:%p -i {{ key_path }} -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null {{ bastion_user }}@{{ bastion_host }}"'