all:
  children:
    k3s_cluster:
      children:
        master:
          hosts:
            dev-master-1:
              ansible_host: 3.226.184.140
              private_ip: 10.0.0.178
              dns_name: ec2-3-226-184-140.compute-1.amazonaws.com
              ansible_ssh_private_key_file: ../aws-terraform-infrastructure/keys/dev-master-1.pem
        worker:
          hosts:
            dev-worker-1:
              ansible_host: 54.173.85.145
              private_ip: 10.0.0.181
              ansible_ssh_private_key_file: ../aws-terraform-infrastructure/keys/dev-worker-1.pem
