# roles/cluster/tasks/06-ingress.yml
---
- name: Create Ingress
  k8s:
    definition:
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: wordpress
        namespace: default
      spec:
        ingressClassName: nginx
        rules:
        - host: "{{ common_name | replace('http://', '') | replace('https://', '') }}"
          http:
            paths:
            - path: /
              pathType: Prefix
              backend:
                service:
                  name: wordpress
                  port:
                    number: 80
