# roles/cluster/tasks/main.yml
---
- name: Install pip3 if not present
  ansible.builtin.apt:
    name: python3-pip
    state: present
  become: true

- name: Install Python Kubernetes library if not present
  ansible.builtin.pip:
    name: kubernetes
    executable: pip3
    state: present
  become: true

- include_tasks: 01-config-map.yml
- include_tasks: 02-secret.yml
- include_tasks: 03-mysql-service.yml
- include_tasks: 04-mysql-statefulset.yml
- include_tasks: 05-wordpress.yml
- include_tasks: 06-ingress.yml