# roles/haproxy/tasks/main.yml
---
- name: Install HAProxy if not installed
  ansible.builtin.package:
    name: haproxy
    state: present
    update_cache: true

- name: Create certificate directory
  ansible.builtin.file:
    path: "{{ haproxy_cert_dir }}"
    state: directory
    mode: '0700'

- name: Combine Server Key and Certificate
  ansible.builtin.shell: |
    cat {{ ca_dir }}/server.key {{ ca_dir }}/server.crt > {{ haproxy_combined_cert }}
    chmod 0600 {{ haproxy_combined_cert }}
  args:
    creates: "{{ haproxy_combined_cert }}"

- name: Create HAProxy configuration
  ansible.builtin.template:
    src: templates/haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    owner: root
    group: root
    mode: '0644'
  notify: Restart HAProxy

- name: Enable and start HAProxy service
  ansible.builtin.systemd:
    name: haproxy
    enabled: true
    state: started
