# roles/ca/tasks/main.yml
---
- name: Ensure OpenSSL is installed
  ansible.builtin.package:
    name: openssl
    state: present

- name: Create a directory to share
  ansible.builtin.file:
    path: "{{ ca_dir }}"
    state: directory
    owner: www-data
    group: www-data
    mode: '0700'

# Tạo CA Private Key
- name: Generate Root CA Key
  openssl_privatekey:
    path: "{{ ca_dir }}/rootCA.key"
    size: "{{ ca_key_size }}"
    type: RSA
    passphrase: "{{ ca_key_passphrase }}"
    cipher: auto

- name: Generate Root CA CSR
  openssl_csr:
    path: "{{ ca_dir }}/rootCA.csr"
    privatekey_path: "{{ ca_dir }}/rootCA.key"
    privatekey_passphrase: "{{ ca_key_passphrase }}"
    country_name: "{{ ca_country }}"
    state_or_province_name: "{{ ca_state }}"
    locality_name: "{{ ca_locality }}"
    organization_name: "{{ ca_organization }}"
    organizational_unit_name: "{{ ca_organizational_unit }}"
    common_name: "{{ ca_common_name | default('Root CA') }}"
    email_address: "{{ ca_email_address }}"
    basic_constraints:
      - 'CA:TRUE'
      - 'pathlen:0'
    basic_constraints_critical: true
    key_usage:
      - digitalSignature
      - keyEncipherment
      - keyCertSign
      - cRLSign
    key_usage_critical: true
    extended_key_usage:
      - serverAuth
      - clientAuth

# Tự ký certificate
- name: Generate Root CA Certificate
  openssl_certificate:
    path: "{{ ca_cert_file }}"
    privatekey_path: "{{ ca_key_file }}"
    privatekey_passphrase: "{{ ca_key_passphrase }}"
    csr_path: "{{ ca_dir }}/rootCA.csr"
    provider: selfsigned
    selfsigned_not_after: "+{{ ca_cert_days }}d"
