{{- if .Values.wordpress.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wordpress
  namespace: default
spec:
  ingressClassName: {{ .Values.wordpress.ingress.className }}
  rules:
    - host: {{ .Values.wordpress.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: wordpress
                port:
                  number: 80
{{- end }}