apiVersion: v1
kind: PersistentVolume
metadata:
  name: wp-pv
  namespace: default
  labels:
    app: wordpress
spec:
  storageClassName: {{ .Values.wordpress.persistence.storageClass }}
  capacity:
    storage: {{ .Values.wordpress.persistence.size }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: "{{ .Values.wordpress.nfs.shareFolder }}"
    server: {{ .Values.wordpress.nfs.server }}