apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-pv-claim
  namespace: default
  labels:
    app: wordpress
spec:
  storageClassName: {{ .Values.wordpress.persistence.storageClass }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.wordpress.persistence.size }}