---
- name: Uninstall K3s from worker nodes
  hosts: worker  # Định nghĩa group các worker nodes trong inventory
  become: yes  # Chạy với quyền sudo
  tasks:
    - name: Check if k3s-agent service exists
      stat:
        path: /etc/systemd/system/k3s-agent.service
      register: k3s_service_file

    - name: Stop k3s-agent service if exists
      systemd:
        name: k3s-agent
        state: stopped
        enabled: no
      when: k3s_service_file.stat.exists

    - name: Kill all k3s processes
      shell: |
        pkill -9 k3s-agent || true
        pkill -9 containerd || true
      ignore_errors: yes

    - name: Run k3s-agent-uninstall.sh script if exists
      shell: /usr/local/bin/k3s-agent-uninstall.sh
      ignore_errors: yes
      when: k3s_service_file.stat.exists

    - name: Remove k3s directories and files
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /var/lib/rancher/k3s
        - /etc/rancher/k3s
        - /var/lib/kubelet
        - /usr/local/bin/k3s
        - /usr/local/bin/kubectl
        - /etc/systemd/system/k3s-agent.service
        - /usr/local/bin/k3s-agent-uninstall.sh

    - name: Remove CNI configurations
      file:
        path: /etc/cni
        state: absent

    - name: Clean up network interfaces
      shell: |
        ip link delete flannel.1 || true
        ip link delete cni0 || true
        ip link delete vxlan.calico || true
      ignore_errors: yes

    - name: Reload systemd
      systemd:
        daemon_reload: yes

    - name: Clean up iptables
      shell: |
        iptables -F
        iptables -X
        iptables -t nat -F
        iptables -t nat -X
        iptables -t mangle -F
        iptables -t mangle -X
      ignore_errors: yes

    - name: Remove container runtime data
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /run/containerd
        - /var/run/containerd
        - /var/lib/containerd