# roles/ssl-certificate/tasks/main.yml
---
- name: Ensure OpenSSL is installed
  ansible.builtin.package:
    name: openssl
    state: present

- name: Create a directory to share
  ansible.builtin.file:
    path: "{{ ssl_certificate_folder }}"
    state: directory
    owner: www-data
    group: www-data
    mode: '0755'

- name: Generate Root CA Key
  openssl_privatekey:
    path: "{{ ssl_certificate_folder }}/rootCA.key"
    size: "{{ key_size }}"
    type: RSA
    passphrase: your_secure_passphrase
    cipher: auto

- name: Generate Root CA Certificate
  openssl_certificate:
    path: "{{ ssl_certificate_folder }}/rootCA.pem"
    privatekey_path: "{{ ssl_certificate_folder }}/rootCA.key"
    privatekey_passphrase: your_secure_passphrase
    provider: selfsigned
    selfsigned_not_after: +1024d

- name: Create server.csr.cnf file
  ansible.builtin.template:
    src: server.csr.cnf.j2
    dest: "{{ ssl_certificate_folder }}/server.csr.cnf"
    mode: '0644'

- name: Create v3.ext file
  ansible.builtin.template:
    src: v3.ext.j2
    dest: "{{ ssl_certificate_folder }}/v3.ext"
    mode: '0644'

- name: Generate Server Private Key
  openssl_privatekey:
    path: "{{ ssl_certificate_folder }}/server.key"
    size: "{{ key_size }}"
    type: RSA

- name: Generate Server CSR
  openssl_csr:
    path: "{{ ssl_certificate_folder }}/server.csr"
    privatekey_path: "{{ ssl_certificate_folder }}/server.key"
    common_name: "{{ common_name }}"
    country_name: "{{ country }}"
    state_or_province_name: "{{ state }}"
    locality_name: "{{ locality }}"
    organization_name: "{{ organization }}"
    organizational_unit_name: "{{ organizational_unit }}"
    email_address: "{{ email_address }}"

- name: Generate Server Certificate
  openssl_certificate:
    path: "{{ ssl_certificate_folder }}/server.crt"
    csr_path: "{{ ssl_certificate_folder }}/server.csr"
    ownca_path: "{{ ssl_certificate_folder }}/rootCA.pem"
    ownca_privatekey_path: "{{ ssl_certificate_folder }}/rootCA.key"
    ownca_privatekey_passphrase: your_secure_passphrase
    provider: ownca
    ownca_not_after: +{{ days_valid }}d
    ownca_create_subject_key_identifier: always_create
    ownca_create_authority_key_identifier: true

- name: Combine Server Key and Certificate
  ansible.builtin.shell: cat {{ ssl_certificate_folder }}/server.key {{ ssl_certificate_folder }}/server.crt > {{ ssl_certificate_folder }}/server.pem
  args:
    creates: "{{ ssl_certificate_folder }}/server.pem"

- name: Set correct permissions for server.pem
  ansible.builtin.file:
    path: "{{ ssl_certificate_folder }}/server.pem"
    mode: '0600'
